namespace QuanLyDeTai.PKHCN.QuanLyDT
{
    partial class modal
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(modal));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.KinhPhi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.HT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TT = new Guna.UI2.WinForms.Guna2ComboBox();
            this.TenDT = new Bunifu.UI.WinForms.BunifuTextBox();
            this.MDT = new Bunifu.UI.WinForms.BunifuTextBox();
            this.panel2 = new System.Windows.Forms.Panel();
            this.guna2HtmlLabel2 = new Guna.UI2.WinForms.Guna2HtmlLabel();
            this.NgayBD = new Bunifu.UI.WinForms.BunifuTextBox();
            this.NgayNT = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TienDo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.NamHoc = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.panel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // KinhPhi
            // 
            this.KinhPhi.AcceptsReturn = false;
            this.KinhPhi.AcceptsTab = false;
            this.KinhPhi.AnimationSpeed = 200;
            this.KinhPhi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.KinhPhi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.KinhPhi.BackColor = System.Drawing.Color.Transparent;
            this.KinhPhi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("KinhPhi.BackgroundImage")));
            this.KinhPhi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.KinhPhi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.KinhPhi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.KinhPhi.BorderColorIdle = System.Drawing.Color.Silver;
            this.KinhPhi.BorderRadius = 1;
            this.KinhPhi.BorderThickness = 1;
            this.KinhPhi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.KinhPhi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.KinhPhi.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.KinhPhi.DefaultText = "";
            this.KinhPhi.FillColor = System.Drawing.Color.White;
            this.KinhPhi.HideSelection = true;
            this.KinhPhi.IconLeft = null;
            this.KinhPhi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.KinhPhi.IconPadding = 10;
            this.KinhPhi.IconRight = null;
            this.KinhPhi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.KinhPhi.Lines = new string[0];
            this.KinhPhi.Location = new System.Drawing.Point(231, 305);
            this.KinhPhi.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.KinhPhi.MaxLength = 32767;
            this.KinhPhi.MinimumSize = new System.Drawing.Size(1, 1);
            this.KinhPhi.Modified = false;
            this.KinhPhi.Multiline = false;
            this.KinhPhi.Name = "KinhPhi";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KinhPhi.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.KinhPhi.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KinhPhi.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KinhPhi.OnIdleState = stateProperties4;
            this.KinhPhi.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.KinhPhi.PasswordChar = '\0';
            this.KinhPhi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.KinhPhi.PlaceholderText = "Kinh Phí";
            this.KinhPhi.ReadOnly = false;
            this.KinhPhi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.KinhPhi.SelectedText = "";
            this.KinhPhi.SelectionLength = 0;
            this.KinhPhi.SelectionStart = 0;
            this.KinhPhi.ShortcutsEnabled = true;
            this.KinhPhi.Size = new System.Drawing.Size(347, 42);
            this.KinhPhi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.KinhPhi.TabIndex = 3;
            this.KinhPhi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.KinhPhi.TextMarginBottom = 0;
            this.KinhPhi.TextMarginLeft = 3;
            this.KinhPhi.TextMarginTop = 0;
            this.KinhPhi.TextPlaceholder = "Kinh Phí";
            this.KinhPhi.UseSystemPasswordChar = false;
            this.KinhPhi.WordWrap = true;
            // 
            // HT
            // 
            this.HT.AllowAnimations = true;
            this.HT.AllowMouseEffects = true;
            this.HT.AllowToggling = false;
            this.HT.AnimationSpeed = 200;
            this.HT.AutoGenerateColors = false;
            this.HT.AutoRoundBorders = false;
            this.HT.AutoSizeLeftIcon = true;
            this.HT.AutoSizeRightIcon = true;
            this.HT.BackColor = System.Drawing.Color.Transparent;
            this.HT.BackColor1 = System.Drawing.Color.LimeGreen;
            this.HT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("HT.BackgroundImage")));
            this.HT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HT.ButtonText = "Lưu";
            this.HT.ButtonTextMarginLeft = 0;
            this.HT.ColorContrastOnClick = 45;
            this.HT.ColorContrastOnHover = 45;
            this.HT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.HT.CustomizableEdges = borderEdges1;
            this.HT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.HT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.HT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.HT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.HT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.HT.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.HT.ForeColor = System.Drawing.Color.White;
            this.HT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.HT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.HT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.HT.IconMarginLeft = 11;
            this.HT.IconPadding = 10;
            this.HT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.HT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.HT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.HT.IconSize = 25;
            this.HT.IdleBorderColor = System.Drawing.Color.LimeGreen;
            this.HT.IdleBorderRadius = 1;
            this.HT.IdleBorderThickness = 1;
            this.HT.IdleFillColor = System.Drawing.Color.LimeGreen;
            this.HT.IdleIconLeftImage = null;
            this.HT.IdleIconRightImage = null;
            this.HT.IndicateFocus = false;
            this.HT.Location = new System.Drawing.Point(231, 715);
            this.HT.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.HT.Name = "HT";
            this.HT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.HT.OnDisabledState.BorderRadius = 1;
            this.HT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HT.OnDisabledState.BorderThickness = 1;
            this.HT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.HT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.HT.OnDisabledState.IconLeftImage = null;
            this.HT.OnDisabledState.IconRightImage = null;
            this.HT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.HT.onHoverState.BorderRadius = 1;
            this.HT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HT.onHoverState.BorderThickness = 1;
            this.HT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.HT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.HT.onHoverState.IconLeftImage = null;
            this.HT.onHoverState.IconRightImage = null;
            this.HT.OnIdleState.BorderColor = System.Drawing.Color.LimeGreen;
            this.HT.OnIdleState.BorderRadius = 1;
            this.HT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HT.OnIdleState.BorderThickness = 1;
            this.HT.OnIdleState.FillColor = System.Drawing.Color.LimeGreen;
            this.HT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.HT.OnIdleState.IconLeftImage = null;
            this.HT.OnIdleState.IconRightImage = null;
            this.HT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.HT.OnPressedState.BorderRadius = 1;
            this.HT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HT.OnPressedState.BorderThickness = 1;
            this.HT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.HT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.HT.OnPressedState.IconLeftImage = null;
            this.HT.OnPressedState.IconRightImage = null;
            this.HT.Size = new System.Drawing.Size(119, 48);
            this.HT.TabIndex = 12;
            this.HT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.HT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.HT.TextMarginLeft = 0;
            this.HT.TextPadding = new System.Windows.Forms.Padding(0);
            this.HT.UseDefaultRadiusAndThickness = true;
            this.HT.Click += new System.EventHandler(this.HT_Click);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Hủy";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges2;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton2.IdleBorderRadius = 1;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(459, 715);
            this.bunifuButton2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(119, 48);
            this.bunifuButton2.TabIndex = 13;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // TT
            // 
            this.TT.BackColor = System.Drawing.Color.Transparent;
            this.TT.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.TT.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.TT.FocusedColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.TT.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.TT.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.TT.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(88)))), ((int)(((byte)(112)))));
            this.TT.ItemHeight = 30;
            this.TT.Items.AddRange(new object[] {
            "Chờ phê duyệt",
            "Đang làm",
            "Đã hoàn thành"});
            this.TT.Location = new System.Drawing.Point(1211, 156);
            this.TT.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TT.Name = "TT";
            this.TT.Size = new System.Drawing.Size(345, 36);
            this.TT.TabIndex = 14;
            this.TT.SelectedIndexChanged += new System.EventHandler(this.TT_SelectedIndexChanged);
            // 
            // TenDT
            // 
            this.TenDT.AcceptsReturn = false;
            this.TenDT.AcceptsTab = false;
            this.TenDT.AnimationSpeed = 200;
            this.TenDT.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TenDT.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TenDT.BackColor = System.Drawing.Color.Transparent;
            this.TenDT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TenDT.BackgroundImage")));
            this.TenDT.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TenDT.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TenDT.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TenDT.BorderColorIdle = System.Drawing.Color.Silver;
            this.TenDT.BorderRadius = 1;
            this.TenDT.BorderThickness = 1;
            this.TenDT.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TenDT.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TenDT.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TenDT.DefaultText = "";
            this.TenDT.FillColor = System.Drawing.Color.White;
            this.TenDT.HideSelection = true;
            this.TenDT.IconLeft = null;
            this.TenDT.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TenDT.IconPadding = 10;
            this.TenDT.IconRight = null;
            this.TenDT.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TenDT.Lines = new string[0];
            this.TenDT.Location = new System.Drawing.Point(708, 156);
            this.TenDT.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TenDT.MaxLength = 32767;
            this.TenDT.MinimumSize = new System.Drawing.Size(1, 1);
            this.TenDT.Modified = false;
            this.TenDT.Multiline = false;
            this.TenDT.Name = "TenDT";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TenDT.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TenDT.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TenDT.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TenDT.OnIdleState = stateProperties8;
            this.TenDT.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TenDT.PasswordChar = '\0';
            this.TenDT.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TenDT.PlaceholderText = "Nhập tên đề tài";
            this.TenDT.ReadOnly = false;
            this.TenDT.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TenDT.SelectedText = "";
            this.TenDT.SelectionLength = 0;
            this.TenDT.SelectionStart = 0;
            this.TenDT.ShortcutsEnabled = true;
            this.TenDT.Size = new System.Drawing.Size(347, 42);
            this.TenDT.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TenDT.TabIndex = 4;
            this.TenDT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TenDT.TextMarginBottom = 0;
            this.TenDT.TextMarginLeft = 3;
            this.TenDT.TextMarginTop = 0;
            this.TenDT.TextPlaceholder = "Nhập tên đề tài";
            this.TenDT.UseSystemPasswordChar = false;
            this.TenDT.WordWrap = true;
            // 
            // MDT
            // 
            this.MDT.AcceptsReturn = false;
            this.MDT.AcceptsTab = false;
            this.MDT.AnimationSpeed = 200;
            this.MDT.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.MDT.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.MDT.BackColor = System.Drawing.Color.Transparent;
            this.MDT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MDT.BackgroundImage")));
            this.MDT.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.MDT.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MDT.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MDT.BorderColorIdle = System.Drawing.Color.Silver;
            this.MDT.BorderRadius = 1;
            this.MDT.BorderThickness = 1;
            this.MDT.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.MDT.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.MDT.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.MDT.DefaultText = "";
            this.MDT.FillColor = System.Drawing.Color.White;
            this.MDT.HideSelection = true;
            this.MDT.IconLeft = null;
            this.MDT.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.MDT.IconPadding = 10;
            this.MDT.IconRight = null;
            this.MDT.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.MDT.Lines = new string[0];
            this.MDT.Location = new System.Drawing.Point(231, 155);
            this.MDT.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.MDT.MaxLength = 32767;
            this.MDT.MinimumSize = new System.Drawing.Size(1, 1);
            this.MDT.Modified = false;
            this.MDT.Multiline = false;
            this.MDT.Name = "MDT";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MDT.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.MDT.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MDT.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MDT.OnIdleState = stateProperties12;
            this.MDT.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.MDT.PasswordChar = '\0';
            this.MDT.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.MDT.PlaceholderText = "Nhập mã đề tài";
            this.MDT.ReadOnly = false;
            this.MDT.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.MDT.SelectedText = "";
            this.MDT.SelectionLength = 0;
            this.MDT.SelectionStart = 0;
            this.MDT.ShortcutsEnabled = true;
            this.MDT.Size = new System.Drawing.Size(347, 46);
            this.MDT.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.MDT.TabIndex = 0;
            this.MDT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.MDT.TextMarginBottom = 0;
            this.MDT.TextMarginLeft = 3;
            this.MDT.TextMarginTop = 0;
            this.MDT.TextPlaceholder = "Nhập mã đề tài";
            this.MDT.UseSystemPasswordChar = false;
            this.MDT.WordWrap = true;
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.bunifuLabel8);
            this.panel2.Controls.Add(this.bunifuLabel7);
            this.panel2.Controls.Add(this.bunifuLabel6);
            this.panel2.Controls.Add(this.bunifuLabel5);
            this.panel2.Controls.Add(this.bunifuLabel4);
            this.panel2.Controls.Add(this.bunifuLabel3);
            this.panel2.Controls.Add(this.bunifuLabel2);
            this.panel2.Controls.Add(this.bunifuLabel1);
            this.panel2.Controls.Add(this.guna2HtmlLabel2);
            this.panel2.Controls.Add(this.NgayBD);
            this.panel2.Controls.Add(this.NgayNT);
            this.panel2.Controls.Add(this.TienDo);
            this.panel2.Controls.Add(this.NamHoc);
            this.panel2.Controls.Add(this.MDT);
            this.panel2.Controls.Add(this.TenDT);
            this.panel2.Controls.Add(this.TT);
            this.panel2.Controls.Add(this.bunifuButton2);
            this.panel2.Controls.Add(this.HT);
            this.panel2.Controls.Add(this.KinhPhi);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(1920, 916);
            this.panel2.TabIndex = 16;
            // 
            // guna2HtmlLabel2
            // 
            this.guna2HtmlLabel2.BackColor = System.Drawing.Color.Transparent;
            this.guna2HtmlLabel2.Font = new System.Drawing.Font("Times New Roman", 21.75F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.guna2HtmlLabel2.Location = new System.Drawing.Point(684, -75);
            this.guna2HtmlLabel2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.guna2HtmlLabel2.Name = "guna2HtmlLabel2";
            this.guna2HtmlLabel2.Size = new System.Drawing.Size(459, 44);
            this.guna2HtmlLabel2.TabIndex = 21;
            this.guna2HtmlLabel2.Text = "Sửa đề tài nghiên cứu khoa học\r\n";
            // 
            // NgayBD
            // 
            this.NgayBD.AcceptsReturn = false;
            this.NgayBD.AcceptsTab = false;
            this.NgayBD.AnimationSpeed = 200;
            this.NgayBD.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.NgayBD.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.NgayBD.BackColor = System.Drawing.Color.Transparent;
            this.NgayBD.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NgayBD.BackgroundImage")));
            this.NgayBD.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.NgayBD.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NgayBD.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NgayBD.BorderColorIdle = System.Drawing.Color.Silver;
            this.NgayBD.BorderRadius = 1;
            this.NgayBD.BorderThickness = 1;
            this.NgayBD.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.NgayBD.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.NgayBD.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.NgayBD.DefaultText = "";
            this.NgayBD.FillColor = System.Drawing.Color.White;
            this.NgayBD.HideSelection = true;
            this.NgayBD.IconLeft = null;
            this.NgayBD.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.NgayBD.IconPadding = 10;
            this.NgayBD.IconRight = null;
            this.NgayBD.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.NgayBD.Lines = new string[0];
            this.NgayBD.Location = new System.Drawing.Point(231, 446);
            this.NgayBD.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.NgayBD.MaxLength = 32767;
            this.NgayBD.MinimumSize = new System.Drawing.Size(1, 1);
            this.NgayBD.Modified = false;
            this.NgayBD.Multiline = false;
            this.NgayBD.Name = "NgayBD";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NgayBD.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.NgayBD.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NgayBD.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NgayBD.OnIdleState = stateProperties16;
            this.NgayBD.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.NgayBD.PasswordChar = '\0';
            this.NgayBD.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.NgayBD.PlaceholderText = "Ngày bắt đầu";
            this.NgayBD.ReadOnly = false;
            this.NgayBD.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.NgayBD.SelectedText = "";
            this.NgayBD.SelectionLength = 0;
            this.NgayBD.SelectionStart = 0;
            this.NgayBD.ShortcutsEnabled = true;
            this.NgayBD.Size = new System.Drawing.Size(347, 42);
            this.NgayBD.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.NgayBD.TabIndex = 19;
            this.NgayBD.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.NgayBD.TextMarginBottom = 0;
            this.NgayBD.TextMarginLeft = 3;
            this.NgayBD.TextMarginTop = 0;
            this.NgayBD.TextPlaceholder = "Ngày bắt đầu";
            this.NgayBD.UseSystemPasswordChar = false;
            this.NgayBD.WordWrap = true;
            // 
            // NgayNT
            // 
            this.NgayNT.AcceptsReturn = false;
            this.NgayNT.AcceptsTab = false;
            this.NgayNT.AnimationSpeed = 200;
            this.NgayNT.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.NgayNT.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.NgayNT.BackColor = System.Drawing.Color.Transparent;
            this.NgayNT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NgayNT.BackgroundImage")));
            this.NgayNT.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.NgayNT.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NgayNT.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NgayNT.BorderColorIdle = System.Drawing.Color.Silver;
            this.NgayNT.BorderRadius = 1;
            this.NgayNT.BorderThickness = 1;
            this.NgayNT.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.NgayNT.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.NgayNT.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.NgayNT.DefaultText = "";
            this.NgayNT.FillColor = System.Drawing.Color.White;
            this.NgayNT.HideSelection = true;
            this.NgayNT.IconLeft = null;
            this.NgayNT.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.NgayNT.IconPadding = 10;
            this.NgayNT.IconRight = null;
            this.NgayNT.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.NgayNT.Lines = new string[0];
            this.NgayNT.Location = new System.Drawing.Point(708, 446);
            this.NgayNT.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.NgayNT.MaxLength = 32767;
            this.NgayNT.MinimumSize = new System.Drawing.Size(1, 1);
            this.NgayNT.Modified = false;
            this.NgayNT.Multiline = false;
            this.NgayNT.Name = "NgayNT";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NgayNT.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.NgayNT.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NgayNT.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NgayNT.OnIdleState = stateProperties20;
            this.NgayNT.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.NgayNT.PasswordChar = '\0';
            this.NgayNT.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.NgayNT.PlaceholderText = "Ngày Nghiệm Thu";
            this.NgayNT.ReadOnly = false;
            this.NgayNT.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.NgayNT.SelectedText = "";
            this.NgayNT.SelectionLength = 0;
            this.NgayNT.SelectionStart = 0;
            this.NgayNT.ShortcutsEnabled = true;
            this.NgayNT.Size = new System.Drawing.Size(347, 42);
            this.NgayNT.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.NgayNT.TabIndex = 18;
            this.NgayNT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.NgayNT.TextMarginBottom = 0;
            this.NgayNT.TextMarginLeft = 3;
            this.NgayNT.TextMarginTop = 0;
            this.NgayNT.TextPlaceholder = "Ngày Nghiệm Thu";
            this.NgayNT.UseSystemPasswordChar = false;
            this.NgayNT.WordWrap = true;
            // 
            // TienDo
            // 
            this.TienDo.AcceptsReturn = false;
            this.TienDo.AcceptsTab = false;
            this.TienDo.AnimationSpeed = 200;
            this.TienDo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TienDo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TienDo.BackColor = System.Drawing.Color.Transparent;
            this.TienDo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TienDo.BackgroundImage")));
            this.TienDo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TienDo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TienDo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TienDo.BorderColorIdle = System.Drawing.Color.Silver;
            this.TienDo.BorderRadius = 1;
            this.TienDo.BorderThickness = 1;
            this.TienDo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TienDo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TienDo.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TienDo.DefaultText = "";
            this.TienDo.FillColor = System.Drawing.Color.White;
            this.TienDo.HideSelection = true;
            this.TienDo.IconLeft = null;
            this.TienDo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TienDo.IconPadding = 10;
            this.TienDo.IconRight = null;
            this.TienDo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TienDo.Lines = new string[0];
            this.TienDo.Location = new System.Drawing.Point(708, 305);
            this.TienDo.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TienDo.MaxLength = 32767;
            this.TienDo.MinimumSize = new System.Drawing.Size(1, 1);
            this.TienDo.Modified = false;
            this.TienDo.Multiline = false;
            this.TienDo.Name = "TienDo";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TienDo.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TienDo.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TienDo.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TienDo.OnIdleState = stateProperties24;
            this.TienDo.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TienDo.PasswordChar = '\0';
            this.TienDo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TienDo.PlaceholderText = "Tiến độ";
            this.TienDo.ReadOnly = false;
            this.TienDo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TienDo.SelectedText = "";
            this.TienDo.SelectionLength = 0;
            this.TienDo.SelectionStart = 0;
            this.TienDo.ShortcutsEnabled = true;
            this.TienDo.Size = new System.Drawing.Size(347, 42);
            this.TienDo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TienDo.TabIndex = 16;
            this.TienDo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TienDo.TextMarginBottom = 0;
            this.TienDo.TextMarginLeft = 3;
            this.TienDo.TextMarginTop = 0;
            this.TienDo.TextPlaceholder = "Tiến độ";
            this.TienDo.UseSystemPasswordChar = false;
            this.TienDo.WordWrap = true;
            // 
            // NamHoc
            // 
            this.NamHoc.AcceptsReturn = false;
            this.NamHoc.AcceptsTab = false;
            this.NamHoc.AnimationSpeed = 200;
            this.NamHoc.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.NamHoc.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.NamHoc.BackColor = System.Drawing.Color.Transparent;
            this.NamHoc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NamHoc.BackgroundImage")));
            this.NamHoc.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.NamHoc.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NamHoc.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NamHoc.BorderColorIdle = System.Drawing.Color.Silver;
            this.NamHoc.BorderRadius = 1;
            this.NamHoc.BorderThickness = 1;
            this.NamHoc.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.NamHoc.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.NamHoc.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.NamHoc.DefaultText = "";
            this.NamHoc.FillColor = System.Drawing.Color.White;
            this.NamHoc.HideSelection = true;
            this.NamHoc.IconLeft = null;
            this.NamHoc.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.NamHoc.IconPadding = 10;
            this.NamHoc.IconRight = null;
            this.NamHoc.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.NamHoc.Lines = new string[0];
            this.NamHoc.Location = new System.Drawing.Point(1209, 305);
            this.NamHoc.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.NamHoc.MaxLength = 32767;
            this.NamHoc.MinimumSize = new System.Drawing.Size(1, 1);
            this.NamHoc.Modified = false;
            this.NamHoc.Multiline = false;
            this.NamHoc.Name = "NamHoc";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NamHoc.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.NamHoc.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NamHoc.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NamHoc.OnIdleState = stateProperties28;
            this.NamHoc.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.NamHoc.PasswordChar = '\0';
            this.NamHoc.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.NamHoc.PlaceholderText = "Năm Học";
            this.NamHoc.ReadOnly = false;
            this.NamHoc.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.NamHoc.SelectedText = "";
            this.NamHoc.SelectionLength = 0;
            this.NamHoc.SelectionStart = 0;
            this.NamHoc.ShortcutsEnabled = true;
            this.NamHoc.Size = new System.Drawing.Size(347, 42);
            this.NamHoc.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.NamHoc.TabIndex = 15;
            this.NamHoc.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.NamHoc.TextMarginBottom = 0;
            this.NamHoc.TextMarginLeft = 3;
            this.NamHoc.TextMarginTop = 0;
            this.NamHoc.TextPlaceholder = "Năm Học";
            this.NamHoc.UseSystemPasswordChar = false;
            this.NamHoc.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(231, 131);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(47, 17);
            this.bunifuLabel1.TabIndex = 22;
            this.bunifuLabel1.Text = "Mã DT";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(708, 132);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(51, 17);
            this.bunifuLabel2.TabIndex = 23;
            this.bunifuLabel2.Text = "Tên DT";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(1211, 132);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(97, 17);
            this.bunifuLabel3.TabIndex = 24;
            this.bunifuLabel3.Text = "Trạng Thái DT";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(231, 281);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(82, 17);
            this.bunifuLabel4.TabIndex = 25;
            this.bunifuLabel4.Text = "Kinh Phí DT";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.Location = new System.Drawing.Point(712, 281);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(78, 17);
            this.bunifuLabel5.TabIndex = 26;
            this.bunifuLabel5.Text = "Tiến Độ DT";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(1211, 281);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(61, 17);
            this.bunifuLabel6.TabIndex = 27;
            this.bunifuLabel6.Text = "Năm Học";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.Location = new System.Drawing.Point(231, 422);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(90, 17);
            this.bunifuLabel7.TabIndex = 28;
            this.bunifuLabel7.Text = "Ngày Bắt Đầu";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.Location = new System.Drawing.Point(712, 422);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(118, 17);
            this.bunifuLabel8.TabIndex = 29;
            this.bunifuLabel8.Text = "Ngày Nghiệm Thu";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // modal
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1924, 916);
            this.Controls.Add(this.panel2);
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "modal";
            this.Text = " ";
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuTextBox KinhPhi;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton HT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Guna.UI2.WinForms.Guna2ComboBox TT;
        private Bunifu.UI.WinForms.BunifuTextBox TenDT;
        private Bunifu.UI.WinForms.BunifuTextBox MDT;
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuTextBox NgayNT;
        private Bunifu.UI.WinForms.BunifuTextBox TienDo;
        private Bunifu.UI.WinForms.BunifuTextBox NamHoc;
        private Bunifu.UI.WinForms.BunifuTextBox NgayBD;
        private Guna.UI2.WinForms.Guna2HtmlLabel guna2HtmlLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
    }
}