namespace QuanLyDeTai.User.Infor
{
    partial class Infor
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Infor));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.colorDialog1 = new System.Windows.Forms.ColorDialog();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.huy = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Edit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Save = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Capbac = new Bunifu.UI.WinForms.BunifuTextBox();
            this.MaBM = new Bunifu.UI.WinForms.BunifuTextBox();
            this.hoten = new Bunifu.UI.WinForms.BunifuTextBox();
            this.chucvu = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(89, 85);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(66, 24);
            this.label1.TabIndex = 6;
            this.label1.Text = "Họ tên";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(89, 290);
            this.label2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(106, 24);
            this.label2.TabIndex = 7;
            this.label2.Text = "Mã bộ môn";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(89, 215);
            this.label4.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(80, 24);
            this.label4.TabIndex = 9;
            this.label4.Text = "Chức vụ";
            this.label4.Click += new System.EventHandler(this.label4_Click);
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(89, 155);
            this.label5.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(80, 24);
            this.label5.TabIndex = 10;
            this.label5.Text = "Cập bậc";
            // 
            // huy
            // 
            this.huy.AllowAnimations = true;
            this.huy.AllowMouseEffects = true;
            this.huy.AllowToggling = false;
            this.huy.AnimationSpeed = 200;
            this.huy.AutoGenerateColors = false;
            this.huy.AutoRoundBorders = false;
            this.huy.AutoSizeLeftIcon = true;
            this.huy.AutoSizeRightIcon = true;
            this.huy.BackColor = System.Drawing.Color.Transparent;
            this.huy.BackColor1 = System.Drawing.Color.Red;
            this.huy.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("huy.BackgroundImage")));
            this.huy.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.ButtonText = "Hủy";
            this.huy.ButtonTextMarginLeft = 0;
            this.huy.ColorContrastOnClick = 45;
            this.huy.ColorContrastOnHover = 45;
            this.huy.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.huy.CustomizableEdges = borderEdges1;
            this.huy.DialogResult = System.Windows.Forms.DialogResult.None;
            this.huy.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.huy.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.huy.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.huy.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.huy.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.huy.ForeColor = System.Drawing.Color.White;
            this.huy.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.huy.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.huy.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.huy.IconMarginLeft = 11;
            this.huy.IconPadding = 10;
            this.huy.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.huy.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.huy.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.huy.IconSize = 25;
            this.huy.IdleBorderColor = System.Drawing.Color.White;
            this.huy.IdleBorderRadius = 1;
            this.huy.IdleBorderThickness = 1;
            this.huy.IdleFillColor = System.Drawing.Color.Red;
            this.huy.IdleIconLeftImage = null;
            this.huy.IdleIconRightImage = null;
            this.huy.IndicateFocus = false;
            this.huy.Location = new System.Drawing.Point(639, 433);
            this.huy.Margin = new System.Windows.Forms.Padding(4);
            this.huy.Name = "huy";
            this.huy.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.huy.OnDisabledState.BorderRadius = 1;
            this.huy.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.OnDisabledState.BorderThickness = 1;
            this.huy.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.huy.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.huy.OnDisabledState.IconLeftImage = null;
            this.huy.OnDisabledState.IconRightImage = null;
            this.huy.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.huy.onHoverState.BorderRadius = 1;
            this.huy.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.onHoverState.BorderThickness = 1;
            this.huy.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.huy.onHoverState.ForeColor = System.Drawing.Color.White;
            this.huy.onHoverState.IconLeftImage = null;
            this.huy.onHoverState.IconRightImage = null;
            this.huy.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.huy.OnIdleState.BorderRadius = 1;
            this.huy.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.OnIdleState.BorderThickness = 1;
            this.huy.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.huy.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.huy.OnIdleState.IconLeftImage = null;
            this.huy.OnIdleState.IconRightImage = null;
            this.huy.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.huy.OnPressedState.BorderRadius = 1;
            this.huy.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.OnPressedState.BorderThickness = 1;
            this.huy.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.huy.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.huy.OnPressedState.IconLeftImage = null;
            this.huy.OnPressedState.IconRightImage = null;
            this.huy.Size = new System.Drawing.Size(112, 48);
            this.huy.TabIndex = 29;
            this.huy.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.huy.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.huy.TextMarginLeft = 0;
            this.huy.TextPadding = new System.Windows.Forms.Padding(0);
            this.huy.UseDefaultRadiusAndThickness = true;
            this.huy.Click += new System.EventHandler(this.huy_Click_1);
            // 
            // Edit
            // 
            this.Edit.AllowAnimations = true;
            this.Edit.AllowMouseEffects = true;
            this.Edit.AllowToggling = false;
            this.Edit.AnimationSpeed = 200;
            this.Edit.AutoGenerateColors = false;
            this.Edit.AutoRoundBorders = false;
            this.Edit.AutoSizeLeftIcon = true;
            this.Edit.AutoSizeRightIcon = true;
            this.Edit.BackColor = System.Drawing.Color.Transparent;
            this.Edit.BackColor1 = System.Drawing.Color.Orange;
            this.Edit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Edit.BackgroundImage")));
            this.Edit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.ButtonText = "Sửa";
            this.Edit.ButtonTextMarginLeft = 0;
            this.Edit.ColorContrastOnClick = 45;
            this.Edit.ColorContrastOnHover = 45;
            this.Edit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Edit.CustomizableEdges = borderEdges2;
            this.Edit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Edit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Edit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Edit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Edit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Edit.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Edit.ForeColor = System.Drawing.Color.White;
            this.Edit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Edit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Edit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Edit.IconMarginLeft = 11;
            this.Edit.IconPadding = 10;
            this.Edit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Edit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Edit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Edit.IconSize = 25;
            this.Edit.IdleBorderColor = System.Drawing.Color.White;
            this.Edit.IdleBorderRadius = 1;
            this.Edit.IdleBorderThickness = 1;
            this.Edit.IdleFillColor = System.Drawing.Color.Orange;
            this.Edit.IdleIconLeftImage = null;
            this.Edit.IdleIconRightImage = null;
            this.Edit.IndicateFocus = false;
            this.Edit.Location = new System.Drawing.Point(224, 433);
            this.Edit.Margin = new System.Windows.Forms.Padding(4);
            this.Edit.Name = "Edit";
            this.Edit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Edit.OnDisabledState.BorderRadius = 1;
            this.Edit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.OnDisabledState.BorderThickness = 1;
            this.Edit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Edit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Edit.OnDisabledState.IconLeftImage = null;
            this.Edit.OnDisabledState.IconRightImage = null;
            this.Edit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Edit.onHoverState.BorderRadius = 1;
            this.Edit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.onHoverState.BorderThickness = 1;
            this.Edit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Edit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Edit.onHoverState.IconLeftImage = null;
            this.Edit.onHoverState.IconRightImage = null;
            this.Edit.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.Edit.OnIdleState.BorderRadius = 1;
            this.Edit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.OnIdleState.BorderThickness = 1;
            this.Edit.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.Edit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Edit.OnIdleState.IconLeftImage = null;
            this.Edit.OnIdleState.IconRightImage = null;
            this.Edit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Edit.OnPressedState.BorderRadius = 1;
            this.Edit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.OnPressedState.BorderThickness = 1;
            this.Edit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Edit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Edit.OnPressedState.IconLeftImage = null;
            this.Edit.OnPressedState.IconRightImage = null;
            this.Edit.Size = new System.Drawing.Size(124, 48);
            this.Edit.TabIndex = 28;
            this.Edit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Edit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Edit.TextMarginLeft = 0;
            this.Edit.TextPadding = new System.Windows.Forms.Padding(0);
            this.Edit.UseDefaultRadiusAndThickness = true;
            this.Edit.Click += new System.EventHandler(this.Edit_Click_1);
            // 
            // Save
            // 
            this.Save.AllowAnimations = true;
            this.Save.AllowMouseEffects = true;
            this.Save.AllowToggling = false;
            this.Save.AnimationSpeed = 200;
            this.Save.AutoGenerateColors = false;
            this.Save.AutoRoundBorders = false;
            this.Save.AutoSizeLeftIcon = true;
            this.Save.AutoSizeRightIcon = true;
            this.Save.BackColor = System.Drawing.Color.Transparent;
            this.Save.BackColor1 = System.Drawing.Color.LimeGreen;
            this.Save.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Save.BackgroundImage")));
            this.Save.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.ButtonText = "Lưu";
            this.Save.ButtonTextMarginLeft = 0;
            this.Save.ColorContrastOnClick = 45;
            this.Save.ColorContrastOnHover = 45;
            this.Save.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Save.CustomizableEdges = borderEdges3;
            this.Save.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Save.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Save.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Save.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Save.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Save.ForeColor = System.Drawing.Color.White;
            this.Save.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Save.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Save.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Save.IconMarginLeft = 11;
            this.Save.IconPadding = 10;
            this.Save.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Save.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Save.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Save.IconSize = 25;
            this.Save.IdleBorderColor = System.Drawing.Color.White;
            this.Save.IdleBorderRadius = 1;
            this.Save.IdleBorderThickness = 1;
            this.Save.IdleFillColor = System.Drawing.Color.LimeGreen;
            this.Save.IdleIconLeftImage = null;
            this.Save.IdleIconRightImage = null;
            this.Save.IndicateFocus = false;
            this.Save.Location = new System.Drawing.Point(422, 433);
            this.Save.Margin = new System.Windows.Forms.Padding(4);
            this.Save.Name = "Save";
            this.Save.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save.OnDisabledState.BorderRadius = 1;
            this.Save.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.OnDisabledState.BorderThickness = 1;
            this.Save.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Save.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Save.OnDisabledState.IconLeftImage = null;
            this.Save.OnDisabledState.IconRightImage = null;
            this.Save.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Save.onHoverState.BorderRadius = 1;
            this.Save.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.onHoverState.BorderThickness = 1;
            this.Save.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Save.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Save.onHoverState.IconLeftImage = null;
            this.Save.onHoverState.IconRightImage = null;
            this.Save.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.Save.OnIdleState.BorderRadius = 1;
            this.Save.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.OnIdleState.BorderThickness = 1;
            this.Save.OnIdleState.FillColor = System.Drawing.Color.LimeGreen;
            this.Save.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Save.OnIdleState.IconLeftImage = null;
            this.Save.OnIdleState.IconRightImage = null;
            this.Save.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Save.OnPressedState.BorderRadius = 1;
            this.Save.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.OnPressedState.BorderThickness = 1;
            this.Save.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Save.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Save.OnPressedState.IconLeftImage = null;
            this.Save.OnPressedState.IconRightImage = null;
            this.Save.Size = new System.Drawing.Size(123, 48);
            this.Save.TabIndex = 27;
            this.Save.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Save.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Save.TextMarginLeft = 0;
            this.Save.TextPadding = new System.Windows.Forms.Padding(0);
            this.Save.UseDefaultRadiusAndThickness = true;
            this.Save.Click += new System.EventHandler(this.Save_Click_1);
            // 
            // Capbac
            // 
            this.Capbac.AcceptsReturn = false;
            this.Capbac.AcceptsTab = false;
            this.Capbac.AnimationSpeed = 200;
            this.Capbac.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Capbac.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Capbac.BackColor = System.Drawing.Color.Transparent;
            this.Capbac.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Capbac.BackgroundImage")));
            this.Capbac.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Capbac.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Capbac.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Capbac.BorderColorIdle = System.Drawing.Color.Silver;
            this.Capbac.BorderRadius = 1;
            this.Capbac.BorderThickness = 1;
            this.Capbac.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Capbac.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Capbac.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Capbac.DefaultText = "";
            this.Capbac.FillColor = System.Drawing.Color.White;
            this.Capbac.HideSelection = true;
            this.Capbac.IconLeft = null;
            this.Capbac.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Capbac.IconPadding = 10;
            this.Capbac.IconRight = null;
            this.Capbac.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Capbac.Lines = new string[0];
            this.Capbac.Location = new System.Drawing.Point(224, 139);
            this.Capbac.Margin = new System.Windows.Forms.Padding(4);
            this.Capbac.MaxLength = 32767;
            this.Capbac.MinimumSize = new System.Drawing.Size(1, 1);
            this.Capbac.Modified = false;
            this.Capbac.Multiline = false;
            this.Capbac.Name = "Capbac";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Capbac.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Capbac.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Capbac.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Capbac.OnIdleState = stateProperties4;
            this.Capbac.Padding = new System.Windows.Forms.Padding(4);
            this.Capbac.PasswordChar = '\0';
            this.Capbac.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Capbac.PlaceholderText = "Enter text";
            this.Capbac.ReadOnly = false;
            this.Capbac.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Capbac.SelectedText = "";
            this.Capbac.SelectionLength = 0;
            this.Capbac.SelectionStart = 0;
            this.Capbac.ShortcutsEnabled = true;
            this.Capbac.Size = new System.Drawing.Size(371, 49);
            this.Capbac.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Capbac.TabIndex = 25;
            this.Capbac.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Capbac.TextMarginBottom = 0;
            this.Capbac.TextMarginLeft = 3;
            this.Capbac.TextMarginTop = 0;
            this.Capbac.TextPlaceholder = "Enter text";
            this.Capbac.UseSystemPasswordChar = false;
            this.Capbac.WordWrap = true;
            // 
            // MaBM
            // 
            this.MaBM.AcceptsReturn = false;
            this.MaBM.AcceptsTab = false;
            this.MaBM.AnimationSpeed = 200;
            this.MaBM.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.MaBM.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.MaBM.BackColor = System.Drawing.Color.Transparent;
            this.MaBM.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MaBM.BackgroundImage")));
            this.MaBM.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.MaBM.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MaBM.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MaBM.BorderColorIdle = System.Drawing.Color.Silver;
            this.MaBM.BorderRadius = 1;
            this.MaBM.BorderThickness = 1;
            this.MaBM.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.MaBM.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.MaBM.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MaBM.DefaultText = "";
            this.MaBM.FillColor = System.Drawing.Color.White;
            this.MaBM.HideSelection = true;
            this.MaBM.IconLeft = null;
            this.MaBM.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.MaBM.IconPadding = 10;
            this.MaBM.IconRight = null;
            this.MaBM.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.MaBM.Lines = new string[0];
            this.MaBM.Location = new System.Drawing.Point(224, 278);
            this.MaBM.Margin = new System.Windows.Forms.Padding(4);
            this.MaBM.MaxLength = 32767;
            this.MaBM.MinimumSize = new System.Drawing.Size(1, 1);
            this.MaBM.Modified = false;
            this.MaBM.Multiline = false;
            this.MaBM.Name = "MaBM";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MaBM.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.MaBM.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MaBM.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MaBM.OnIdleState = stateProperties8;
            this.MaBM.Padding = new System.Windows.Forms.Padding(4);
            this.MaBM.PasswordChar = '\0';
            this.MaBM.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.MaBM.PlaceholderText = "Enter text";
            this.MaBM.ReadOnly = false;
            this.MaBM.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.MaBM.SelectedText = "";
            this.MaBM.SelectionLength = 0;
            this.MaBM.SelectionStart = 0;
            this.MaBM.ShortcutsEnabled = true;
            this.MaBM.Size = new System.Drawing.Size(371, 49);
            this.MaBM.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.MaBM.TabIndex = 20;
            this.MaBM.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.MaBM.TextMarginBottom = 0;
            this.MaBM.TextMarginLeft = 3;
            this.MaBM.TextMarginTop = 0;
            this.MaBM.TextPlaceholder = "Enter text";
            this.MaBM.UseSystemPasswordChar = false;
            this.MaBM.WordWrap = true;
            this.MaBM.TextChanged += new System.EventHandler(this.MaBM_TextChanged);
            // 
            // hoten
            // 
            this.hoten.AcceptsReturn = false;
            this.hoten.AcceptsTab = false;
            this.hoten.AnimationSpeed = 200;
            this.hoten.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.hoten.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.hoten.BackColor = System.Drawing.Color.Transparent;
            this.hoten.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hoten.BackgroundImage")));
            this.hoten.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.hoten.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hoten.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hoten.BorderColorIdle = System.Drawing.Color.Silver;
            this.hoten.BorderRadius = 1;
            this.hoten.BorderThickness = 1;
            this.hoten.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.hoten.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.hoten.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.hoten.DefaultText = "";
            this.hoten.FillColor = System.Drawing.Color.White;
            this.hoten.HideSelection = true;
            this.hoten.IconLeft = null;
            this.hoten.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.hoten.IconPadding = 10;
            this.hoten.IconRight = null;
            this.hoten.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.hoten.Lines = new string[0];
            this.hoten.Location = new System.Drawing.Point(224, 70);
            this.hoten.Margin = new System.Windows.Forms.Padding(4);
            this.hoten.MaxLength = 32767;
            this.hoten.MinimumSize = new System.Drawing.Size(1, 1);
            this.hoten.Modified = false;
            this.hoten.Multiline = false;
            this.hoten.Name = "hoten";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.hoten.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.hoten.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.hoten.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.hoten.OnIdleState = stateProperties12;
            this.hoten.Padding = new System.Windows.Forms.Padding(4);
            this.hoten.PasswordChar = '\0';
            this.hoten.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.hoten.PlaceholderText = "Enter text";
            this.hoten.ReadOnly = false;
            this.hoten.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.hoten.SelectedText = "";
            this.hoten.SelectionLength = 0;
            this.hoten.SelectionStart = 0;
            this.hoten.ShortcutsEnabled = true;
            this.hoten.Size = new System.Drawing.Size(371, 49);
            this.hoten.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.hoten.TabIndex = 19;
            this.hoten.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.hoten.TextMarginBottom = 0;
            this.hoten.TextMarginLeft = 3;
            this.hoten.TextMarginTop = 0;
            this.hoten.TextPlaceholder = "Enter text";
            this.hoten.UseSystemPasswordChar = false;
            this.hoten.WordWrap = true;
            // 
            // chucvu
            // 
            this.chucvu.AcceptsReturn = false;
            this.chucvu.AcceptsTab = false;
            this.chucvu.AnimationSpeed = 200;
            this.chucvu.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.chucvu.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.chucvu.BackColor = System.Drawing.Color.Transparent;
            this.chucvu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("chucvu.BackgroundImage")));
            this.chucvu.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.chucvu.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.chucvu.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chucvu.BorderColorIdle = System.Drawing.Color.Silver;
            this.chucvu.BorderRadius = 1;
            this.chucvu.BorderThickness = 1;
            this.chucvu.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.chucvu.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.chucvu.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chucvu.DefaultText = "";
            this.chucvu.FillColor = System.Drawing.Color.White;
            this.chucvu.HideSelection = true;
            this.chucvu.IconLeft = null;
            this.chucvu.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.chucvu.IconPadding = 10;
            this.chucvu.IconRight = null;
            this.chucvu.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.chucvu.Lines = new string[0];
            this.chucvu.Location = new System.Drawing.Point(224, 205);
            this.chucvu.Margin = new System.Windows.Forms.Padding(4);
            this.chucvu.MaxLength = 32767;
            this.chucvu.MinimumSize = new System.Drawing.Size(1, 1);
            this.chucvu.Modified = false;
            this.chucvu.Multiline = false;
            this.chucvu.Name = "chucvu";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.chucvu.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.chucvu.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.chucvu.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.chucvu.OnIdleState = stateProperties16;
            this.chucvu.Padding = new System.Windows.Forms.Padding(4);
            this.chucvu.PasswordChar = '\0';
            this.chucvu.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.chucvu.PlaceholderText = "Enter text";
            this.chucvu.ReadOnly = false;
            this.chucvu.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.chucvu.SelectedText = "";
            this.chucvu.SelectionLength = 0;
            this.chucvu.SelectionStart = 0;
            this.chucvu.ShortcutsEnabled = true;
            this.chucvu.Size = new System.Drawing.Size(371, 49);
            this.chucvu.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.chucvu.TabIndex = 30;
            this.chucvu.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.chucvu.TextMarginBottom = 0;
            this.chucvu.TextMarginLeft = 3;
            this.chucvu.TextMarginTop = 0;
            this.chucvu.TextPlaceholder = "Enter text";
            this.chucvu.UseSystemPasswordChar = false;
            this.chucvu.WordWrap = true;
            // 
            // Infor
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1067, 554);
            this.Controls.Add(this.chucvu);
            this.Controls.Add(this.huy);
            this.Controls.Add(this.Edit);
            this.Controls.Add(this.Save);
            this.Controls.Add(this.Capbac);
            this.Controls.Add(this.MaBM);
            this.Controls.Add(this.hoten);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "Infor";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Infor_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.ColorDialog colorDialog1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox hoten;
        private Bunifu.UI.WinForms.BunifuTextBox MaBM;
        private Bunifu.UI.WinForms.BunifuTextBox Capbac;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Save;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Edit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton huy;
        private Bunifu.UI.WinForms.BunifuTextBox chucvu;
    }
}