namespace QuanLyDeTai.DaiDoi.Infor
{
    partial class Infor
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Infor));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.colorDialog1 = new System.Windows.Forms.ColorDialog();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.huy = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Edit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Save = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.QuanSo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.DiaDiem = new Bunifu.UI.WinForms.BunifuTextBox();
            this.MaTD = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TenDV = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(65, 85);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(106, 24);
            this.label1.TabIndex = 6;
            this.label1.Text = "Tên Đơn Vị";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(65, 350);
            this.label2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(120, 24);
            this.label2.TabIndex = 7;
            this.label2.Text = "Mã tiểu đoàn";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(66, 260);
            this.label5.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(85, 24);
            this.label5.TabIndex = 10;
            this.label5.Text = "Quân Số";
            this.label5.Click += new System.EventHandler(this.label5_Click);
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(65, 172);
            this.label7.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(86, 24);
            this.label7.TabIndex = 12;
            this.label7.Text = "Địa Điểm";
            // 
            // huy
            // 
            this.huy.AllowAnimations = true;
            this.huy.AllowMouseEffects = true;
            this.huy.AllowToggling = false;
            this.huy.AnimationSpeed = 200;
            this.huy.AutoGenerateColors = false;
            this.huy.AutoRoundBorders = false;
            this.huy.AutoSizeLeftIcon = true;
            this.huy.AutoSizeRightIcon = true;
            this.huy.BackColor = System.Drawing.Color.Transparent;
            this.huy.BackColor1 = System.Drawing.Color.Red;
            this.huy.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("huy.BackgroundImage")));
            this.huy.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.ButtonText = "Hủy";
            this.huy.ButtonTextMarginLeft = 0;
            this.huy.ColorContrastOnClick = 45;
            this.huy.ColorContrastOnHover = 45;
            this.huy.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.huy.CustomizableEdges = borderEdges1;
            this.huy.DialogResult = System.Windows.Forms.DialogResult.None;
            this.huy.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.huy.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.huy.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.huy.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.huy.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.huy.ForeColor = System.Drawing.Color.White;
            this.huy.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.huy.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.huy.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.huy.IconMarginLeft = 11;
            this.huy.IconPadding = 10;
            this.huy.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.huy.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.huy.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.huy.IconSize = 25;
            this.huy.IdleBorderColor = System.Drawing.Color.White;
            this.huy.IdleBorderRadius = 1;
            this.huy.IdleBorderThickness = 1;
            this.huy.IdleFillColor = System.Drawing.Color.Red;
            this.huy.IdleIconLeftImage = null;
            this.huy.IdleIconRightImage = null;
            this.huy.IndicateFocus = false;
            this.huy.Location = new System.Drawing.Point(581, 464);
            this.huy.Margin = new System.Windows.Forms.Padding(4);
            this.huy.Name = "huy";
            this.huy.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.huy.OnDisabledState.BorderRadius = 1;
            this.huy.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.OnDisabledState.BorderThickness = 1;
            this.huy.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.huy.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.huy.OnDisabledState.IconLeftImage = null;
            this.huy.OnDisabledState.IconRightImage = null;
            this.huy.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.huy.onHoverState.BorderRadius = 1;
            this.huy.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.onHoverState.BorderThickness = 1;
            this.huy.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.huy.onHoverState.ForeColor = System.Drawing.Color.White;
            this.huy.onHoverState.IconLeftImage = null;
            this.huy.onHoverState.IconRightImage = null;
            this.huy.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.huy.OnIdleState.BorderRadius = 1;
            this.huy.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.OnIdleState.BorderThickness = 1;
            this.huy.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.huy.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.huy.OnIdleState.IconLeftImage = null;
            this.huy.OnIdleState.IconRightImage = null;
            this.huy.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.huy.OnPressedState.BorderRadius = 1;
            this.huy.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.OnPressedState.BorderThickness = 1;
            this.huy.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.huy.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.huy.OnPressedState.IconLeftImage = null;
            this.huy.OnPressedState.IconRightImage = null;
            this.huy.Size = new System.Drawing.Size(112, 48);
            this.huy.TabIndex = 29;
            this.huy.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.huy.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.huy.TextMarginLeft = 0;
            this.huy.TextPadding = new System.Windows.Forms.Padding(0);
            this.huy.UseDefaultRadiusAndThickness = true;
            this.huy.Click += new System.EventHandler(this.huy_Click_1);
            // 
            // Edit
            // 
            this.Edit.AllowAnimations = true;
            this.Edit.AllowMouseEffects = true;
            this.Edit.AllowToggling = false;
            this.Edit.AnimationSpeed = 200;
            this.Edit.AutoGenerateColors = false;
            this.Edit.AutoRoundBorders = false;
            this.Edit.AutoSizeLeftIcon = true;
            this.Edit.AutoSizeRightIcon = true;
            this.Edit.BackColor = System.Drawing.Color.Transparent;
            this.Edit.BackColor1 = System.Drawing.Color.Orange;
            this.Edit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Edit.BackgroundImage")));
            this.Edit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.ButtonText = "Sửa";
            this.Edit.ButtonTextMarginLeft = 0;
            this.Edit.ColorContrastOnClick = 45;
            this.Edit.ColorContrastOnHover = 45;
            this.Edit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Edit.CustomizableEdges = borderEdges2;
            this.Edit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Edit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Edit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Edit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Edit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Edit.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Edit.ForeColor = System.Drawing.Color.White;
            this.Edit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Edit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Edit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Edit.IconMarginLeft = 11;
            this.Edit.IconPadding = 10;
            this.Edit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Edit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Edit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Edit.IconSize = 25;
            this.Edit.IdleBorderColor = System.Drawing.Color.White;
            this.Edit.IdleBorderRadius = 1;
            this.Edit.IdleBorderThickness = 1;
            this.Edit.IdleFillColor = System.Drawing.Color.Orange;
            this.Edit.IdleIconLeftImage = null;
            this.Edit.IdleIconRightImage = null;
            this.Edit.IndicateFocus = false;
            this.Edit.Location = new System.Drawing.Point(168, 464);
            this.Edit.Margin = new System.Windows.Forms.Padding(4);
            this.Edit.Name = "Edit";
            this.Edit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Edit.OnDisabledState.BorderRadius = 1;
            this.Edit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.OnDisabledState.BorderThickness = 1;
            this.Edit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Edit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Edit.OnDisabledState.IconLeftImage = null;
            this.Edit.OnDisabledState.IconRightImage = null;
            this.Edit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Edit.onHoverState.BorderRadius = 1;
            this.Edit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.onHoverState.BorderThickness = 1;
            this.Edit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Edit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Edit.onHoverState.IconLeftImage = null;
            this.Edit.onHoverState.IconRightImage = null;
            this.Edit.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.Edit.OnIdleState.BorderRadius = 1;
            this.Edit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.OnIdleState.BorderThickness = 1;
            this.Edit.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.Edit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Edit.OnIdleState.IconLeftImage = null;
            this.Edit.OnIdleState.IconRightImage = null;
            this.Edit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Edit.OnPressedState.BorderRadius = 1;
            this.Edit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.OnPressedState.BorderThickness = 1;
            this.Edit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Edit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Edit.OnPressedState.IconLeftImage = null;
            this.Edit.OnPressedState.IconRightImage = null;
            this.Edit.Size = new System.Drawing.Size(124, 48);
            this.Edit.TabIndex = 28;
            this.Edit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Edit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Edit.TextMarginLeft = 0;
            this.Edit.TextPadding = new System.Windows.Forms.Padding(0);
            this.Edit.UseDefaultRadiusAndThickness = true;
            this.Edit.Click += new System.EventHandler(this.Edit_Click_1);
            // 
            // Save
            // 
            this.Save.AllowAnimations = true;
            this.Save.AllowMouseEffects = true;
            this.Save.AllowToggling = false;
            this.Save.AnimationSpeed = 200;
            this.Save.AutoGenerateColors = false;
            this.Save.AutoRoundBorders = false;
            this.Save.AutoSizeLeftIcon = true;
            this.Save.AutoSizeRightIcon = true;
            this.Save.BackColor = System.Drawing.Color.Transparent;
            this.Save.BackColor1 = System.Drawing.Color.LimeGreen;
            this.Save.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Save.BackgroundImage")));
            this.Save.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.ButtonText = "Lưu";
            this.Save.ButtonTextMarginLeft = 0;
            this.Save.ColorContrastOnClick = 45;
            this.Save.ColorContrastOnHover = 45;
            this.Save.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Save.CustomizableEdges = borderEdges3;
            this.Save.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Save.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Save.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Save.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Save.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Save.ForeColor = System.Drawing.Color.White;
            this.Save.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Save.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Save.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Save.IconMarginLeft = 11;
            this.Save.IconPadding = 10;
            this.Save.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Save.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Save.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Save.IconSize = 25;
            this.Save.IdleBorderColor = System.Drawing.Color.White;
            this.Save.IdleBorderRadius = 1;
            this.Save.IdleBorderThickness = 1;
            this.Save.IdleFillColor = System.Drawing.Color.LimeGreen;
            this.Save.IdleIconLeftImage = null;
            this.Save.IdleIconRightImage = null;
            this.Save.IndicateFocus = false;
            this.Save.Location = new System.Drawing.Point(386, 464);
            this.Save.Margin = new System.Windows.Forms.Padding(4);
            this.Save.Name = "Save";
            this.Save.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save.OnDisabledState.BorderRadius = 1;
            this.Save.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.OnDisabledState.BorderThickness = 1;
            this.Save.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Save.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Save.OnDisabledState.IconLeftImage = null;
            this.Save.OnDisabledState.IconRightImage = null;
            this.Save.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Save.onHoverState.BorderRadius = 1;
            this.Save.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.onHoverState.BorderThickness = 1;
            this.Save.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Save.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Save.onHoverState.IconLeftImage = null;
            this.Save.onHoverState.IconRightImage = null;
            this.Save.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.Save.OnIdleState.BorderRadius = 1;
            this.Save.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.OnIdleState.BorderThickness = 1;
            this.Save.OnIdleState.FillColor = System.Drawing.Color.LimeGreen;
            this.Save.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Save.OnIdleState.IconLeftImage = null;
            this.Save.OnIdleState.IconRightImage = null;
            this.Save.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Save.OnPressedState.BorderRadius = 1;
            this.Save.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.OnPressedState.BorderThickness = 1;
            this.Save.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Save.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Save.OnPressedState.IconLeftImage = null;
            this.Save.OnPressedState.IconRightImage = null;
            this.Save.Size = new System.Drawing.Size(123, 48);
            this.Save.TabIndex = 27;
            this.Save.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Save.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Save.TextMarginLeft = 0;
            this.Save.TextPadding = new System.Windows.Forms.Padding(0);
            this.Save.UseDefaultRadiusAndThickness = true;
            this.Save.Click += new System.EventHandler(this.Save_Click_1);
            // 
            // QuanSo
            // 
            this.QuanSo.AcceptsReturn = false;
            this.QuanSo.AcceptsTab = false;
            this.QuanSo.AnimationSpeed = 200;
            this.QuanSo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.QuanSo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.QuanSo.BackColor = System.Drawing.Color.Transparent;
            this.QuanSo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("QuanSo.BackgroundImage")));
            this.QuanSo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.QuanSo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.QuanSo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.QuanSo.BorderColorIdle = System.Drawing.Color.Silver;
            this.QuanSo.BorderRadius = 1;
            this.QuanSo.BorderThickness = 1;
            this.QuanSo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.QuanSo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.QuanSo.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.QuanSo.DefaultText = "";
            this.QuanSo.FillColor = System.Drawing.Color.White;
            this.QuanSo.HideSelection = true;
            this.QuanSo.IconLeft = null;
            this.QuanSo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.QuanSo.IconPadding = 10;
            this.QuanSo.IconRight = null;
            this.QuanSo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.QuanSo.Lines = new string[0];
            this.QuanSo.Location = new System.Drawing.Point(205, 245);
            this.QuanSo.Margin = new System.Windows.Forms.Padding(4);
            this.QuanSo.MaxLength = 32767;
            this.QuanSo.MinimumSize = new System.Drawing.Size(1, 1);
            this.QuanSo.Modified = false;
            this.QuanSo.Multiline = false;
            this.QuanSo.Name = "QuanSo";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QuanSo.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.QuanSo.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QuanSo.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QuanSo.OnIdleState = stateProperties4;
            this.QuanSo.Padding = new System.Windows.Forms.Padding(4);
            this.QuanSo.PasswordChar = '\0';
            this.QuanSo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.QuanSo.PlaceholderText = "Enter text";
            this.QuanSo.ReadOnly = false;
            this.QuanSo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.QuanSo.SelectedText = "";
            this.QuanSo.SelectionLength = 0;
            this.QuanSo.SelectionStart = 0;
            this.QuanSo.ShortcutsEnabled = true;
            this.QuanSo.Size = new System.Drawing.Size(246, 49);
            this.QuanSo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.QuanSo.TabIndex = 25;
            this.QuanSo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.QuanSo.TextMarginBottom = 0;
            this.QuanSo.TextMarginLeft = 3;
            this.QuanSo.TextMarginTop = 0;
            this.QuanSo.TextPlaceholder = "Enter text";
            this.QuanSo.UseSystemPasswordChar = false;
            this.QuanSo.WordWrap = true;
            // 
            // DiaDiem
            // 
            this.DiaDiem.AcceptsReturn = false;
            this.DiaDiem.AcceptsTab = false;
            this.DiaDiem.AnimationSpeed = 200;
            this.DiaDiem.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.DiaDiem.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.DiaDiem.BackColor = System.Drawing.Color.Transparent;
            this.DiaDiem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("DiaDiem.BackgroundImage")));
            this.DiaDiem.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.DiaDiem.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DiaDiem.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.DiaDiem.BorderColorIdle = System.Drawing.Color.Silver;
            this.DiaDiem.BorderRadius = 1;
            this.DiaDiem.BorderThickness = 1;
            this.DiaDiem.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.DiaDiem.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.DiaDiem.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DiaDiem.DefaultText = "";
            this.DiaDiem.FillColor = System.Drawing.Color.White;
            this.DiaDiem.HideSelection = true;
            this.DiaDiem.IconLeft = null;
            this.DiaDiem.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.DiaDiem.IconPadding = 10;
            this.DiaDiem.IconRight = null;
            this.DiaDiem.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.DiaDiem.Lines = new string[0];
            this.DiaDiem.Location = new System.Drawing.Point(205, 158);
            this.DiaDiem.Margin = new System.Windows.Forms.Padding(4);
            this.DiaDiem.MaxLength = 32767;
            this.DiaDiem.MinimumSize = new System.Drawing.Size(1, 1);
            this.DiaDiem.Modified = false;
            this.DiaDiem.Multiline = false;
            this.DiaDiem.Name = "DiaDiem";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.DiaDiem.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.DiaDiem.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.DiaDiem.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.DiaDiem.OnIdleState = stateProperties8;
            this.DiaDiem.Padding = new System.Windows.Forms.Padding(4);
            this.DiaDiem.PasswordChar = '\0';
            this.DiaDiem.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.DiaDiem.PlaceholderText = "Enter text";
            this.DiaDiem.ReadOnly = false;
            this.DiaDiem.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.DiaDiem.SelectedText = "";
            this.DiaDiem.SelectionLength = 0;
            this.DiaDiem.SelectionStart = 0;
            this.DiaDiem.ShortcutsEnabled = true;
            this.DiaDiem.Size = new System.Drawing.Size(246, 49);
            this.DiaDiem.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.DiaDiem.TabIndex = 21;
            this.DiaDiem.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.DiaDiem.TextMarginBottom = 0;
            this.DiaDiem.TextMarginLeft = 3;
            this.DiaDiem.TextMarginTop = 0;
            this.DiaDiem.TextPlaceholder = "Enter text";
            this.DiaDiem.UseSystemPasswordChar = false;
            this.DiaDiem.WordWrap = true;
            // 
            // MaTD
            // 
            this.MaTD.AcceptsReturn = false;
            this.MaTD.AcceptsTab = false;
            this.MaTD.AnimationSpeed = 200;
            this.MaTD.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.MaTD.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.MaTD.BackColor = System.Drawing.Color.Transparent;
            this.MaTD.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MaTD.BackgroundImage")));
            this.MaTD.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.MaTD.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MaTD.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MaTD.BorderColorIdle = System.Drawing.Color.Silver;
            this.MaTD.BorderRadius = 1;
            this.MaTD.BorderThickness = 1;
            this.MaTD.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.MaTD.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.MaTD.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MaTD.DefaultText = "";
            this.MaTD.FillColor = System.Drawing.Color.White;
            this.MaTD.HideSelection = true;
            this.MaTD.IconLeft = null;
            this.MaTD.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.MaTD.IconPadding = 10;
            this.MaTD.IconRight = null;
            this.MaTD.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.MaTD.Lines = new string[0];
            this.MaTD.Location = new System.Drawing.Point(205, 335);
            this.MaTD.Margin = new System.Windows.Forms.Padding(4);
            this.MaTD.MaxLength = 32767;
            this.MaTD.MinimumSize = new System.Drawing.Size(1, 1);
            this.MaTD.Modified = false;
            this.MaTD.Multiline = false;
            this.MaTD.Name = "MaTD";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MaTD.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.MaTD.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MaTD.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MaTD.OnIdleState = stateProperties12;
            this.MaTD.Padding = new System.Windows.Forms.Padding(4);
            this.MaTD.PasswordChar = '\0';
            this.MaTD.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.MaTD.PlaceholderText = "Enter text";
            this.MaTD.ReadOnly = false;
            this.MaTD.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.MaTD.SelectedText = "";
            this.MaTD.SelectionLength = 0;
            this.MaTD.SelectionStart = 0;
            this.MaTD.ShortcutsEnabled = true;
            this.MaTD.Size = new System.Drawing.Size(246, 49);
            this.MaTD.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.MaTD.TabIndex = 20;
            this.MaTD.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.MaTD.TextMarginBottom = 0;
            this.MaTD.TextMarginLeft = 3;
            this.MaTD.TextMarginTop = 0;
            this.MaTD.TextPlaceholder = "Enter text";
            this.MaTD.UseSystemPasswordChar = false;
            this.MaTD.WordWrap = true;
            // 
            // TenDV
            // 
            this.TenDV.AcceptsReturn = false;
            this.TenDV.AcceptsTab = false;
            this.TenDV.AnimationSpeed = 200;
            this.TenDV.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TenDV.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TenDV.BackColor = System.Drawing.Color.Transparent;
            this.TenDV.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TenDV.BackgroundImage")));
            this.TenDV.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TenDV.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TenDV.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TenDV.BorderColorIdle = System.Drawing.Color.Silver;
            this.TenDV.BorderRadius = 1;
            this.TenDV.BorderThickness = 1;
            this.TenDV.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TenDV.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TenDV.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TenDV.DefaultText = "";
            this.TenDV.FillColor = System.Drawing.Color.White;
            this.TenDV.HideSelection = true;
            this.TenDV.IconLeft = null;
            this.TenDV.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TenDV.IconPadding = 10;
            this.TenDV.IconRight = null;
            this.TenDV.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TenDV.Lines = new string[0];
            this.TenDV.Location = new System.Drawing.Point(205, 68);
            this.TenDV.Margin = new System.Windows.Forms.Padding(4);
            this.TenDV.MaxLength = 32767;
            this.TenDV.MinimumSize = new System.Drawing.Size(1, 1);
            this.TenDV.Modified = false;
            this.TenDV.Multiline = false;
            this.TenDV.Name = "TenDV";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TenDV.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TenDV.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TenDV.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TenDV.OnIdleState = stateProperties16;
            this.TenDV.Padding = new System.Windows.Forms.Padding(4);
            this.TenDV.PasswordChar = '\0';
            this.TenDV.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TenDV.PlaceholderText = "Enter text";
            this.TenDV.ReadOnly = false;
            this.TenDV.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TenDV.SelectedText = "";
            this.TenDV.SelectionLength = 0;
            this.TenDV.SelectionStart = 0;
            this.TenDV.ShortcutsEnabled = true;
            this.TenDV.Size = new System.Drawing.Size(246, 49);
            this.TenDV.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TenDV.TabIndex = 19;
            this.TenDV.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TenDV.TextMarginBottom = 0;
            this.TenDV.TextMarginLeft = 3;
            this.TenDV.TextMarginTop = 0;
            this.TenDV.TextPlaceholder = "Enter text";
            this.TenDV.UseSystemPasswordChar = false;
            this.TenDV.WordWrap = true;
            // 
            // Infor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1067, 570);
            this.Controls.Add(this.huy);
            this.Controls.Add(this.Edit);
            this.Controls.Add(this.Save);
            this.Controls.Add(this.QuanSo);
            this.Controls.Add(this.DiaDiem);
            this.Controls.Add(this.MaTD);
            this.Controls.Add(this.TenDV);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "Infor";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Infor_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.ColorDialog colorDialog1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox TenDV;
        private Bunifu.UI.WinForms.BunifuTextBox MaTD;
        private Bunifu.UI.WinForms.BunifuTextBox DiaDiem;
        private Bunifu.UI.WinForms.BunifuTextBox QuanSo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Save;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Edit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton huy;
    }
}